#!/usr/bin/env sh
set -eu

if [ $# -ne 1 ]; then
	echo "usage: $0 ruler_length" 1>&2
	echo "Writes ruler_length hyphens and a newline to stdout." 1>&2
	exit 1
fi

ruler=""
for i in $(seq 1 $1); do
	ruler="${ruler}-"
done

echo "$ruler"
